# Generated by Django 3.0.4 on 2020-05-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200503_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
